<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var \Magento\Backend\Block\Template $block */

$clean = $block->getUrl('*/*/*', ['rebuild' => 1]);
$update = $block->getUrl('*/*/*', ['update' => 1]);

?>
<?= __('<strong>Actions:</strong><br><b>Reset Table</b>: <a href="%1">Click here</a> to clear all data and rebuild in ' .
       'background. Should also be executed when new Customer Group Mapping is added' .
       '<br><b>Update</b>: <a href="%2">Click here</a> to update to the most recent data in background', $clean,
    $update); ?>
<hr><?= __('<strong>Notes:</strong><br><b>Qty Sold</b>: Refers to the qty sold at the line price' .
           '<br><b>Deviation</b>: Refers to the deviation from all previous sales up to that point' .
           '<br><b>First Sale At</b>: Refers to the date the first sale was made at line price' .
           '<br><b>Last Sale At</b>: Refers to the date the last sale was made at line price'); ?>

