<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   29/01/20, 15:22 GMT
 *
 */

/** @var \Magento\Backend\Block\Template $block */

$clean = $block->getUrl('*/*/*', ['rebuild' => 1]);
$update = $block->getUrl('*/*/*', ['update' => 1]);

?>
<?= __('<strong>Actions:</strong><br><b>Reset Table</b>: <a href="%1">Click here</a> to clear all data and rebuild in ' .
       'background. Should also be executed when new Customer Group Mapping is added' .
       '<br><b>Update</b>: <a href="%2">Click here</a> to update to the most recent data in background', $clean,
    $update); ?>
<hr><?= __('<strong>Notes:</strong><br><b>Qty Sold</b>: Refers to the qty sold at the line price' .
           '<br><b>Deviation</b>: Refers to the deviation from all previous sales up to that point' .
           '<br><b>First Sale At</b>: Refers to the date the first sale was made at line price' .
           '<br><b>Last Sale At</b>: Refers to the date the last sale was made at line price'); ?>

