<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   03/06/20, 16:19 GMT
 *
 */

/** @var $block \Licentia\Reports\Block\Adminhtml\Searches\InfoCloud */

/** @var $this \Magento\Framework\View\TemplateEngine\Php */

$segments = $block->getSegmentsList();
$start = $block->getRequest()->getParam('interval_start');
$end = $block->getRequest()->getParam('interval_end');

$type = $block->getType();
$group = $block->getGroup();

if ($type == 'country') {
    $possibleCountries = $block->getPossibleCountries();
}

/** @var Licentia\Reports\Helper\Data $update */
$update = $this->helper('Licentia\Reports\Helper\Data')->getRebuildDateforIndexer('search_performance');
?>

<div id="messages">
    <div class="messages">
        <div class="message message-warning warning">
            <div data-ui-id="messages-message-warning">
                <strong><?= __('Last Update') ?>: </strong> <?= $update ?>
                . <?= __('Check the <a target="_blank" href="%1">Indexer</a> status for more info about stats updates',
                    $block->getUrl('*/indexer')) ?>
            </div>
        </div>
    </div>
</div>

<style type="text/css">
    select {
        font: 400 12px/1.3 "Helvetica Neue", sans-serif;
        -webkit-appearance: none;
        appearance: none;
        border: 1px solid #303030;
        line-height: 1;
        outline: 0;
        color: #303030;
        border-color: #303030;
        padding: 0.65em 2.5em 0.55em 0.75em;
        border-radius: 3px;
        background: linear-gradient(#303030, #303030) no-repeat,
        linear-gradient(-135deg, rgba(255, 255, 255, 0) 50%, white 50%) no-repeat,
        linear-gradient(-225deg, rgba(255, 255, 255, 0) 50%, white 50%) no-repeat,
        linear-gradient(#303030, #303030) no-repeat;
        background-color: white;
        background-size: 1px 100%, 20px 20px, 20px 20px, 20px 60%;
        background-position: right 20px center, right bottom, right bottom, right bottom;
    }
</style>
<div id="panda-stats">

    <div class="page-main-actions">
        <div class="page-actions" style="float: left;">

            <div style="float: left;">
                Data Type:
                <select onchange="window.location='<?= /* @noEscape */
                $block->getUrl(
                    '*/*/*',
                    ['_current' => true, 'type' => false, 'region' => false, 'country' => false, 'age' => false]
                ) ?>type/'+this.value;">

                    <?php foreach ($block->getTypes() as $key => $type): ?>
                        <option <?php if ($block->getType() == $key) {
                            echo " selected='selected' ";
                        } ?> value="<?= $block->escapeHtmlAttr($key) ?>">
                            <?= $type ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <?php if ($block->getType() == 'country'): ?>
                <div style="float: left; margin: 0 5px;">
                    Country:
                    <select onchange="window.location='<?= /* @noEscape */
                    $block->getUrl(
                        '*/*/*',
                        ['_current' => true, 'region' => false, 'country' => false, 'age' => false]
                    ) ?>country/'+this.value;">
                        <?php foreach ($block->getPossibleCountries() as $key => $type): ?>
                            <option <?php if ($block->getRequest()->getParam('country') == $key) {
                                echo " selected='selected' ";
                            } ?> value="<?= $block->escapeHtmlAttr($key) ?>">
                                <?= $type ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif; ?>

            <?php if ($block->getType() == 'region'): ?>
                <div style="float: left; margin: 0 5px;">
                    Region:
                    <select onchange="window.location='<?= /* @noEscape */
                    $block->getUrl(
                        '*/*/*',
                        ['_current' => true, 'region' => false, 'country' => false, 'age' => false]
                    ) ?>region/'+this.value;">
                        <?php foreach ($block->getPossibleRegions() as $key => $type): ?>
                            <option <?php if ($block->getRequest()->getParam('region') == $key) {
                                echo " selected='selected' ";
                            } ?> value="<?= $block->escapeHtmlAttr($key) ?>">
                                <?= $type ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif; ?>

            <?php if ($block->getType() == 'age'): ?>
                <div style="float: left; margin: 0 5px;">
                    Age:
                    <select onchange="window.location='<?= /* @noEscape */
                    $block->getUrl(
                        '*/*/*',
                        ['_current' => true, 'region' => false, 'country' => false, 'age' => false]
                    ) ?>age/'+this.value;">
                        <?php foreach ($block->getPossibleAges() as $key => $type): ?>
                            <option <?php if ($block->getRequest()->getParam('age') == $key) {
                                echo " selected='selected' ";
                            } ?> value="<?= $block->escapeHtmlAttr($key) ?>">
                                <?= $type ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif; ?>

        </div>
        <div style="float: right">
            <input type="text" id="date_from" value="<?= $block->escapeHtmlAttr($start) ?>"
                   class="required-entry input-text admin__control-text" name="start_date">

            <input type="text" id="date_to" value="<?= $block->escapeHtmlAttr($end) ?>"
                   class="required-entry input-text admin__control-text" name="end_date">

            <script type="text/javascript">// <![CDATA[
                require(["jquery", "mage/calendar"], function ($) {
                    $("#date_from").calendar({
                        showsTime: false,
                        dateFormat: 'yyyy-mm-dd'
                    });
                    $("#date_to").calendar({
                        showsTime: false,
                        dateFormat: 'yyyy-mm-dd'
                    });

                    $('#changeDate').click(function () {
                        window.location = '<?= $block->getUrl(
                            '*/*/*',
                            [
                                '_current'       => true,
                                'interval_start' => false,
                                'interval_end'   => false,
                            ]
                        ) ?>interval_start/' + $("#date_from").val() + '/interval_end/' + $("#date_to").val();
                    });
                });
            </script>

            <button title="Date" id="changeDate"
                    type="button" class="action-default scalable">
                <span><?= /* @noEscape */
                    __('Apply Date Filter') ?></span>
            </button>

            <?php if ($start || $end): ?>
                <button title="Date" id="changeDate"
                        onclick="window.location='<?= $block->getUrl(
                            '*/*/*',
                            [
                                '_current'       => true,
                                'interval_start' => false,
                                'interval_end'   => false,
                            ]
                        ); ?>'"
                        type="button" class="action-default scalable">
                    <span><?= /* @noEscape */
                        __('Clear Date Filter') ?></span>
                </button>

            <?php endif; ?>

        </div>
        <div style="float: right">
            <?php if (count($segments)): ?>
                <div style="float: left; padding:3px 9px;">
                    <select onchange="window.location='<?= /* @noEscape */
                    $block->getUrl(
                        '*/*/*',
                        [
                            '_current'   => true,
                            'segment_id' => false,
                        ]
                    ) ?>segment_id/'+this.value;"
                            name="segment_id">
                        <option value="">--<?= __('Filter by Segment') ?>--</option>
                        <?php foreach ($segments as $segment): ?>
                            <option <?php if ($segment->getId() == $block->getSegmentId()) {
                                echo " selected='selected' ";
                            } ?> value="<?= $block->escapeHtmlAttr($segment->getId()) ?>"><?= $block->escapeHtml($segment->getName()) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>