<?php
/*
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Licentia\Reports\Block\Adminhtml\Searches\View */

/** @var $this \Magento\Framework\View\TemplateEngine\Php */

$countries = Zend_Locale::getTranslationList('Territory');
$collection = $block->getStatsArray();
$skus = $block->getSKUs();

?>
<style type="text/css">
    select {
        font: 400 12px/1.3 "Helvetica Neue", sans-serif;
        -webkit-appearance: none;
        appearance: none;
        border: 1px solid #303030;
        line-height: 1;
        outline: 0;
        color: #303030;
        border-color: #303030;
        padding: 0.65em 2.5em 0.55em 0.75em;
        border-radius: 3px;
        background: linear-gradient(#303030, #303030) no-repeat,
        linear-gradient(-135deg, rgba(255, 255, 255, 0) 50%, white 50%) no-repeat,
        linear-gradient(-225deg, rgba(255, 255, 255, 0) 50%, white 50%) no-repeat,
        linear-gradient(#303030, #303030) no-repeat;
        background-color: white;
        background-size: 1px 100%, 20px 20px, 20px 20px, 20px 60%;
        background-position: right 20px center, right bottom, right bottom, right bottom;
    }
</style>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script type="text/javascript">

    require(["jquery", "jquery/ui", 'domReady!'], function ($) {

        $("#aquery").on('keypress', function (e) {
            if (e.which === 13) {
                window.location = '<?= $block->getUrl(
                    '*/*/*',
                    ['_current' => true]
                ) ?>query/' + $(this).val();
            }
        }).autocomplete({
            source: "<?= $block->getUrl('*/ajax/search', ['type' => 'search']) ?>",
            minLength: 3,
            select: function (event, ui) {
                window.location = '<?= $block->getUrl(
                    '*/*/*',
                    ['_current' => true]
                ) ?>query/' + ui.item.value;
            }
        });

    });
</script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div class="panda_autocomplete panda-stats">

    <div class="page-main-actions">
        <div class="page-actions" style="float: left; width: 100%">

            <div style="float: left;">
                <?php

                $sku = $block->getRequest()->getParam('query');
                $sku = $block->getSKU() ? $block->getSKU() : false;

                ?>
                <div class="control" style="float: left; margin:0 10px; padding: 5px; ">
                    <input style="padding: 4px; width: 250px;" name="aquery"
                           value="<?= $block->escapeHtmlAttr($block->escapeHtml($sku)) ?>"
                           id="aquery" type="text" class="input text">
                </div>

            </div>

            <div style="float: right">
                <button title="Date" id="changeDate"
                        onclick="window.location='<?= /* @noEscape */
                        $block->getUrl(
                            '*/*/index',
                            [
                                '_current'       => true,
                                'interval_start' => false,
                                'interval_end'   => false,
                                'cloud'          => 1,
                            ]
                        ); ?>'"
                        type="button" class="action-default scalable">
                    <span><?= /* @noEscape */
                        __('Return to Cloud') ?></span>
                </button>
            </div>
        </div>
    </div>

    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <?php foreach (\Licentia\Reports\Model\Search\Stats::REPORT_TYPES as $type) : ?>
            <?php

            if (isset($collection[$type])) :
                foreach ($collection[$type] as $tmpData) : ?>
                    <?php foreach ($tmpData as $range => $data) :
                        if (!is_array($data)) {
                            continue;
                        }
                        ?>

                        <?php $data = array_filter($data); ?>

                        <table class="data-grid" style="width: 47%; float: left; margin:1%;">
                            <thead>
                            <tr class="headings">
                                <th class="data-grid-th "><?php

                                    $typeTitle = __(ucwords($type));
                                    $title = $typeTitle . " / " . $range;

                                    if ($range === 0) {
                                        $title = $typeTitle;
                                    }

                                    if ($type == 'country' && isset($countries[$range])) {
                                        $title = $typeTitle . ' / ' . $countries[$range];
                                    }
                                    echo $title; ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                    <?php

                                    $json = [['Country', 'Total']];
                                    foreach (range(1, 25) as $indexKey) {
                                        if (isset($data['related_' . $indexKey])) {
                                            $json[] = [
                                                $block->getProductName(
                                                    $data['related_' . $indexKey]
                                                ),
                                                (int) $data['related_total_' . $indexKey],
                                            ];
                                        }
                                    }
                                    $json = json_encode($json);

                                    ?>

                                    <script type="text/javascript">
                                        //<![CDATA[

                                        require(['jquery', 'domReady!'], function ($) {


                                            google.charts.load('current', {'packages': ['corechart']});
                                            google.charts.setOnLoadCallback(drawChart);


                                            $(window).resize(function () {
                                                var container = document.getElementById("chart_links<?= /* @noEscape */ $type . $range ?>").firstChild.firstChild;
                                                container.style.width = "100%";
                                                drawChart();
                                            });

                                            function drawChart() {
                                                var data = google.visualization.arrayToDataTable(<?= $json ?>);

                                                var options = {
                                                    tooltip: {trigger: 'selection'},
                                                    legend: {
                                                        textStyle: {
                                                            fontSize: 12
                                                        }
                                                    },
                                                    pieSliceTextStyle: {fontSize: 11},
                                                    pieSliceText: 'value-and-percentage',
                                                    backgroundColor: {fill: 'transparent'},
                                                    chartArea: {
                                                        height: 500,
                                                        width: '100%'
                                                    },
                                                    width: $(window).width / 2,
                                                    height: 500,
                                                    is3D: true,
                                                    colors: ['#83071B', '#870F21', '#8C1827',
                                                        '#91212D', '#962A33', '#9B3239', '#A03B3F',
                                                        '#A44445', '#A94D4B', '#AE5551', '#B35E57', '#B8675D',
                                                        '#BD7063', '#C17869', '#C6816F',
                                                        '#CB8A75', '#D0937B', '#D59B81',
                                                        '#DAA487', '#DEAD8D', '#E3B693',
                                                        '#E8BE99', '#EDC79F', '#F2D0A5',
                                                        '#F7D9AB'
                                                    ]
                                                };

                                                var chart = new google.visualization.PieChart(document.getElementById('chart_links<?= $type . $range ?>'));

                                                chart.setAction({
                                                    id: 'sample',
                                                    text: 'View Query',
                                                    action: function () {
                                                        window.open('<?= /* @noEscape */  $block->getUrl(
                                                            '*/*/*',
                                                            [
                                                                '_current' => true,
                                                                'query'    => false,
                                                            ]
                                                        ) ?>query/' + data.getValue(chart.getSelection()[0].row, 0));
                                                    }
                                                });

                                                chart.draw(data, options);

                                            }

                                        });

                                        //]]>

                                    </script>
                                    <div id="chart_links<?= /* @noEscape */
                                    $type . $range ?>" style="width: 100%"></div>

                                </td>

                            </tr>
                            </tbody>
                        </table>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
