<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   17/03/20, 20:16 GMT
 *
 */

/** @var \Magento\Backend\Block\Template $block */
/** @var Licentia\Reports\Helper\Data $update */
$update = $this->helper('Licentia\Reports\Helper\Data')->getRebuildDateforIndexer('reorders');
?>

<div id="messages">
    <div class="messages">
        <div class="message message-warning warning">
            <div data-ui-id="messages-message-warning">
                <strong><?= __('Last Update') ?>: </strong> <?= $update ?>. <?= __('Check the <a target="_blank" href="%1">Indexer</a> status for more info about stats updates',$block->getUrl('*/indexer')) ?>
            </div>
        </div>
    </div>
</div>
