<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   29/01/20, 15:22 GMT
 *
 */

/** @var $block \Licentia\Reports\Block\Adminhtml\Stats\View */

/** @var $this \Magento\Framework\View\TemplateEngine\Php */

$collection = $block->getStatsArray();
$titles = $block->getColumnsTitles('table');
$skus = $block->getSKUs();
$days = $block->getPeriodsInCollection();
$ages = $block->getAges();
$segments = $block->getSegmentsList();
$currentType = $block->getType();

$bgcolor = [];

if (count($ages) == 1) {
    $rowSpan = count($ages) + count($skus) - 1;
} else {
    $rowSpan = count($ages) * count($skus);
}

$displayChart = $block->getRequest()->getParam('chart');

$hideColors = $block->getRequest()->getParam('hide_colors');

$code = [1 => '&Alpha;', 2 => '&#914;', 3 => '&#915;', 4 => '&#916;', 5 => '&#917;'];
$bgcolorList = [1 => '#CAE1FF', 2 => '#BDFCC9', 3 => '#EEEED1', 4 => '#CDB79E;', 5 => '#A9A9A9'];

$nCodes = [];

if ($currentType != 'attribute') {
    $i = 1;
    foreach ($skus as $sku) {
        $nCodes[$sku] = $code[$i];
        $bgcolor[$sku] = $bgcolorList[$i];
        $i++;
    }
}
$start = $block->getRequest()->getParam('interval_start');
$end = $block->getRequest()->getParam('interval_end');
$titlesChart = $block->getColumnsTitles('chart');

$chart = [];
foreach ($days as $day) {

    foreach (array_keys($titlesChart) as $title) {

        foreach ($ages as $age) {

            foreach ($skus as $sku) {

                $chartKey = $age !== 0 ? $day . ' / ' . $age : $day;

                $chart[$chartKey][$title][$sku] = (int) $collection[$sku][$day][$age][$title];

            }
        }

    }

}

?>
<?php if ($displayChart) : ?>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script type="text/javascript">
        require(['jquery', 'domReady!'], function ($) {


            $('#chart_div').css('height', window.innerHeight + 'px');

            google.charts.load('current', {'packages': ['bar']});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
                var data = new google.visualization.DataTable();
                data.addColumn('string', '');

                <?php foreach ($titlesChart as $title) : ?>
                <?php foreach ($skus as $sku) : ?>
                data.addColumn('number', ' <?= $title . ' [' . $sku . ']' ?> ');
                <?php endforeach;?>
                <?php endforeach;?>


                data.addRows([
                    <?php foreach ($chart as $key => $value) :
                    $tmpValue = [];
                    foreach ($value as $tmp) {
                        $tmpValue[] = implode(',', $tmp);
                    }
                    ?>

                    ['<?= $block->formatPeriodColumn($key); ?>', <?=  implode(',', $tmpValue) ?>],

                    <?php endforeach;?>
                ]);

                var options = {
                    isStacked: true,
                    width: '100%',
                    height: window.innerHeight - 50,
                    series: {
                <?php
                $a = 0;
                for ($i = 0; $i < count($skus); $i++) { ?>

                <?= $a;
                $a++; ?>:
                {
                    targetAxisIndex:  <?=  (count($skus) * 2 / 2 >= $a) ? 0 : 1; ?>
                        }
            ,
                <?= $a;
                $a++; ?>:
                {
                    targetAxisIndex:  <?=  (count($skus) * 2 / 2 >= $a) ? 0 : 1; ?>
                        }
            ,

                <?php } ?>
            }
            }
                var chart = new google.charts.Bar(document.getElementById('chart_div'));
                chart.draw(data, google.charts.Bar.convertOptions(options));
            }
        });

    </script>

<?php endif; ?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script type="text/javascript">

    require(["jquery", "jquery/ui", 'domReady!'], function ($) {


        $('#apply_fields').click(function () {


            window.location = '<?= /* @noEscape */ $block->getUrl(
                '*/*/*',
                ['_current' => true, 'fieldsts' => false]
            ) ?>fieldsts/' + $('.fields_to_select:checkbox:checked').map(function () {
                return this.value;
            }).get().join(',');
        });

        for (i = 1; i <= 5; i++) {
            $("#asku" + i).on('keypress', function (e) {
                if (e.which === 13) {

                    window.location = '<?= $block->getUrl(
                        '*/*/*',
                        ['_current' => true]
                    ) ?>sku' + $(this).attr('data-index') + '/' + $(this).val();

                }
            }).autocomplete({
                source: '<?= $block->getUrl('*/ajax/search') ?>',
                minLength: 3,
                select: function (event, ui) {
                    window.location = '<?= $block->getUrl(
                        '*/*/*',
                        ['_current' => true]
                    ) ?>sku' + $(this).attr('data-index') + '/' + ui.item.value;
                }
            });
        }
    });

</script>
<style type="text/css">
    select {
        font: 400 12px/1.3 "Helvetica Neue", sans-serif;
        -webkit-appearance: none;
        appearance: none;
        border: 1px solid #303030;
        line-height: 1;
        outline: 0;
        color: #303030;
        border-color: #303030;
        padding: 0.65em 2.5em 0.55em 0.75em;
        border-radius: 3px;
        background: linear-gradient(#303030, #303030) no-repeat,
        linear-gradient(-135deg, rgba(255, 255, 255, 0) 50%, white 50%) no-repeat,
        linear-gradient(-225deg, rgba(255, 255, 255, 0) 50%, white 50%) no-repeat,
        linear-gradient(#303030, #303030) no-repeat;
        background-color: white;
        background-size: 1px 100%, 20px 20px, 20px 20px, 20px 60%;
        background-position: right 20px center, right bottom, right bottom, right bottom;
    }
</style>
<div class="panda_autocomplete panda-stats">

    <div class="admin__data-grid-header admin__data-grid-toolbar">

        <div class="admin__data-grid-header-row ">
            <div class="admin__control-support-text">
                        <span><?= count(
                                $days
                            ) ?></span>
                <?= __('records found ') ?>
            </div>
        </div>

    </div>
    <div class="page-main-actions">
        <div class="page-actions" style="float: left;">

            <div style="float: left;">
                Data Type:
                <select onchange="window.location='<?= /* @noEscape */
                $block->getUrl(
                    '*/*/*',
                    ['_current' => true, 'type' => false, 'attribute2' => false, 'attributeValue' => false]
                ) ?>type/'+this.value;">


                    <?php foreach ($block->getTypes() as $key => $type) : ?>
                        <option <?php if ($block->getType() == $key) {
                            echo " selected='selected' ";
                        } ?> value="<?= $block->escapeHtmlAttr($key) ?>">
                            <?= $type ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php if ($block->getType() == 'attribute') : ?>
                <div class="control" style="float: left; padding:0 5px; ">
                    <div style="float:left; padding: 6px;">Attribute</div>

                    <select name="attr" onchange="window.location = '<?= /* @noEscape */
                    $block->getUrl(
                        '*/*/*',
                        [
                            '_current'       => true,
                            'attribute2'     => false,
                            'attributeValue' => false,
                        ]
                    ) ?>attribute/' + this.value">
                        <?php foreach ($block->getPossibleAttributes() as $key => $value) : ?>
                            <option <?php if ($key == $block->getAttribute()) {
                                echo " selected='selected' ";
                            } ?> value="<?= $block->escapeHtmlAttr($key) ?>"><?= $block->escapeHtml($value) ?></option>

                        <?php endforeach; ?>

                    </select>
                </div>

                <?php if ($block->getAttributeValue()) : ?>

                    <div class="control" style="float: left; padding:0 5px; ">
                        <div style="float:left; padding: 6px;">Attr Value:</div>

                        <select name="attr" onchange="window.location = '<?= /* @noEscape */
                        $block->getUrl(
                            '*/*/*',
                            ['_current' => true, 'attributeValue' => false]
                        ) ?>attributeValue/' + this.value">
                            <?php if (!$block->getAttributeValue()) : ?>
                                <option value="">-Choose-</option>
                            <?php endif; ?>
                            <?php foreach ($block->getPossibleAttributesValues() as $key => $value) : ?>
                                <?php if ($key == $block->getAttribute()) {
                                    continue;
                                } ?>
                                <option <?php if ($key == $block->getAttributeValue()) {
                                    echo " selected='selected' ";
                                } ?> value="<?= $block->escapeHtmlAttr($key) ?>"><?= $block->escapeHtml($value) ?></option>

                            <?php endforeach; ?>

                        </select>
                    </div>


                <?php endif; ?>

                <div class="control" style="float: left; padding:0 5px; ">
                    <div style="float:left; padding: 6px;">Against</div>

                    <select name="attr" onchange="window.location = '<?= /* @noEscape */
                    $block->getUrl(
                        '*/*/*',
                        ['_current' => true]
                    ) ?>attribute2/' + this.value">
                        <?php if (!$block->getAttributeValue()) : ?>
                            <option value="">-Choose-</option>
                        <?php endif; ?>
                        <?php foreach ($block->getPossibleAttributes() as $key => $value) : ?>
                            <?php if ($key == $block->getAttribute()) {
                                continue;
                            } ?>
                            <option <?php if ($key == $block->getAttribute2()) {
                                echo " selected='selected' ";
                            } ?> value="<?= $block->escapeHtmlAttr($key) ?>"><?= $block->escapeHtml($value) ?></option>

                        <?php endforeach; ?>

                    </select>
                </div>

            <?php endif; ?>
            <div style="float: left; margin-left:30px;">
                Group:
                <select onchange="window.location='<?= /* @noEscape */
                $block->getUrl(
                    '*/*/*',
                    ['_current' => true, 'group' => false]
                ) ?>group/'+this.value;">
                    <?php foreach ($block->getGroups() as $key => $group) : ?>
                        <option <?php if ($block->getGroup() == $key) {
                            echo " selected='selected' ";
                        } ?> value="<?= $block->escapeHtmlAttr($key) ?>">
                            <?= $group ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php if (count($segments)) : ?>
                <div style="float: left; margin-left:30px;">
                    Segment:
                    <select onchange="window.location='<?= /* @noEscape */
                    $block->getUrl(
                        '*/*/*',
                        [
                            '_current'   => true,
                            'segment_id' => false,
                        ]
                    ) ?>segment_id/'+this.value;"
                            name="segment_id">
                        <option value="">--<?= __('Filter by Segment') ?>--</option>
                        <?php foreach ($segments as $segment) : ?>
                            <option <?php if ($segment->getId() == $block->getSegmentId()) {
                                echo " selected='selected' ";
                            } ?> value="<?= $block->escapeHtmlAttr($segment->getId()) ?>"><?= $block->escapeHtml($segment->getName()) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif; ?>

        </div>
        <div style="float: right; width: 400px;">

            <!--
            <div style="margin:0 10px;">
                <button style="float: right; margin: 0 5px;" title="Export" type="button"
                        class="action-default scalable ">
                    <span>Export to CSV</span>
                </button>
            </div>
            <div style="margin:0 10px;">
                <?php if ($displayChart) : ?>

                    <button onclick="window.location='<?= /* @noEscape */
                $block->getUrl(
                    '*/*/*',
                    ['_current' => true, 'chart' => 0]
                ) ?>'"
                            style="float: right; margin: 0 5px;" type="button" class="action-default scalable ">
                        <span>Hide Chart</span>
                    </button>
                <?php else : ?>
                    <button onclick="window.location='<?= /* @noEscape */
                $block->getUrl(
                    '*/*/*',
                    ['_current' => true, 'chart' => 1]
                ) ?>'"
                            style="float: right; margin: 0 5px;" type="button" class="action-default scalable ">
                        <span>Show Chart</span>
                    </button>
                <?php endif; ?>
            </div>
            <div style="margin:0 10px;">
                <?php if ($hideColors) : ?>

                    <button onclick="window.location='<?= /* @noEscape */
                $block->getUrl(
                    '*/*/*',
                    ['_current' => true, 'hide_colors' => 0]
                ) ?>'"
                            style="float: right; margin: 0 5px;" type="button" class="action-default scalable ">
                        <span>Show Colors</span>
                    </button>
                <?php else : ?>
                    <button onclick="window.location='<?= /* @noEscape */
                $block->getUrl(
                    '*/*/*',
                    ['_current' => true, 'hide_colors' => 1]
                ) ?>'"
                            style="float: right; margin: 0 5px;" type="button" class="action-default scalable ">
                        <span>Hide Colors</span>
                    </button>
                <?php endif; ?>
            </div>
-->
            <div style="margin:0 10px; height: 45px; overflow: hidden">

                <input type="text" id="date_from" value="<?= $block->escapeHtmlAttr($start) ?>"
                       class="required-entry input-text admin__control-text" name="start_date">

                <input type="text" id="date_to" value="<?= $block->escapeHtmlAttr($end) ?>"
                       class="required-entry input-text admin__control-text" name="end_date">

                <script type="text/javascript">// <![CDATA[
                    require(["jquery", "mage/calendar"], function ($) {
                        $("#date_from").calendar({
                            showsTime: false,
                            dateFormat: 'yyyy-mm-dd'
                        });
                        $("#date_to").calendar({
                            showsTime: false,
                            dateFormat: 'yyyy-mm-dd'
                        });

                        $('#changeDate').click(function () {
                            window.location = '<?= /* @noEscape */ $block->getUrl(
                                '*/*/*',
                                [
                                    '_current'       => true,
                                    'interval_start' => false,
                                    'interval_end'   => false,
                                ]
                            ) ?>interval_start/' + $("#date_from").val() + '/interval_end/' + $("#date_to").val();
                        });
                    });
                </script>

                <button title="Date" id="changeDate"
                        type="button" class="action-default scalable">
                    <span><?= /* @noEscape */
                        __('Apply') ?></span>
                </button>

                <?php if ($start || $end) : ?>
                    <button title="Date" id="changeDate"
                            onclick="window.location='<?= /* @noEscape */
                            $block->getUrl(
                                '*/*/*',
                                [
                                    '_current'       => true,
                                    'interval_start' => false,
                                    'interval_end'   => false,
                                ]
                            ); ?>'"
                            type="button" class="action-default scalable">
                        <span><?= /* @noEscape */
                            __('Clear') ?></span>
                    </button>

                <?php endif; ?>

            </div>

        </div>
        <div style="clear: both; float: right;">
            <small>
                <?php foreach ($block->getAvailableFields() as $key => $value) : ?>
                    <input class="fields_to_select" <?php if (array_key_exists($key, $titles)) {
                        echo "  checked='checked' ";
                    } ?> style="margin-left:5px;" type="checkbox" name="fieldsts[]" id="fs<?= $key; ?>"
                           value="<?= $block->escapeHtmlAttr($key) ?>">
                    <label for="fs<?= $key; ?>"><?= $block->escapeHtml($value) ?></label>
                <?php endforeach; ?></small>
            <strong id="apply_fields"
                    style="padding:0 4px; cursor: pointer; background: #e3e3e3;  border:1px solid #adadad;color: #514943;">OK</strong>
        </div>
    </div>

    <?php if ($currentType != 'attribute') : ?>
        <div class="page-main-actions">
            <div class="page-actions" style="float: left;" data-ui-id="page-actions-toolbar-content-header">

                <?php $skip = false;
                for ($i = 1; $i <= 5; $i++) :
                    $sku = $block->getRequest()->getParam('sku' . $i);
                    $sku = isset($block->getSKUs()[$sku]) ? $block->getSKUs()[$sku] : false;

                    if ($skip && !$sku) {
                        continue;
                    }
                    if (!$sku) {
                        $skip = true;
                    } ?>
                    <div class="control"
                         style="float: left; margin:0 10px; padding: 5px; ">
                        <div style="float:left; padding: 6px;">
                            <strong><?= $block->escapeHtml(isset($nCodes[$sku]) ? $nCodes[$sku] : '') ?></strong>
                        </div>
                        <input style="padding: 4px; width: 250px;" name="asku<?= $i; ?>"
                               value="<?= $block->escapeHtmlAttr($block->escapeHtml($sku)) ?>"
                               id="asku<?= $block->escapeHtmlAttr($i) ?>" data-index="<?= $block->escapeHtmlAttr($i) ?>"
                               type="text" class="input text">
                        <?php if ($sku) :
                            ?> <a href="<?= /* @noEscape */
                        $block->getUrl(
                            '*/*/*',
                            ['_current' => true, 'sku' . $i => false]
                        ) ?>"
                                  style=" padding: 1px 6px; border: 2px solid darkred; border-radius: 8px;
                                  background-color: whitesmoke; font-size: 17px; line-height: 9px;color: #2b0000;
                                  font-weight: bolder;">X </a>
                            <div style="padding: 5px 0 0 15px;"><?= $block->escapeHtml($block->getProduct($sku)
                                                                                             ->getName()) ?></div>
                        <?php else : ?>
                            <div style="padding: 5px 0 0 15px;">
                                <small><em><?= /* @noEscape */
                                        __('Start typing to search for product...') ?></em>
                                </small>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endfor; ?>

                <div style="clear: left"></div>

            </div>
        </div>


    <?php endif; ?>
    <?php if (count($collection) > 0) : ?>

    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <?php if ($displayChart) : ?>
            <table class="data-grid" id="id_6e926db1dba3f43970080d5f7a311274_table">
                <thead>
                <tr>
                    <th class="data-grid-th " style="text-align: center; width: 1%">
                        <div><span><?= /* @noEscape */
                                __('Chart') ?></span></div>
                    </th>
                </tr>
                <tr>
                    <td>
                        <div id="chart_div" style="height: 600px;"></div>
                    </td>
                </tr>
                </thead>
            </table>
        <?php endif; ?>
        <table class="data-grid" id="id_6e926db1dba3f43970080d5f7a311274_table">
            <thead>

            <tr>
                <th class="data-grid-th " style="text-align: center; width: 1%">
                    <div><span><?= $block->escapeHtml($block->getIntervalTitle()) ?></span></div>
                </th>
                <?php $previous = '';
                foreach ($titles as $title) : ?>

                    <?php foreach ($skus as $sku) :
                        if ($title == $previous) {
                            $previous = $title;
                            continue;
                        } ?>
                        <th colspan="<?= $block->escapeHtmlAttr($rowSpan) ?>" class="data-grid-th "
                            style="text-align: center; width: 1%">
                            <div><span><?= /* @noEscape */
                                    __($title) ?></span></div>
                        </th>
                        <?php $previous = $title;
                    endforeach; ?>
                <?php endforeach; ?>
            </tr>
            </thead>

            <tbody>
            <?php if ($block->getType() != 'attribute') : ?>
                <tr>
                    <th class="data-grid-th " style="text-align: center; width: 1%">
                        <div><span></span></div>
                    </th>

                    <?php foreach ($titles as $key => $title) : ?>
                        <?php foreach ($skus as $sku) : ?>
                            <th colspan="<?= $block->escapeHtmlAttr(count($ages)) ?>" class="data-grid-th "
                                style="text-align: center; width: 1%">
                                <div>
                                    <span><?= $block->escapeHtml(isset($nCodes[$sku]) ? $nCodes[$sku] : $sku) ?></span>
                                </div>
                            </th>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </tr>
            <?php endif; ?>

            <?php if (count($ages) > 1) : ?>
                <tr class="">
                    <td style="background-color: #accb7e; word-break: keep-all; white-space: nowrap">
                        <small></small>
                    </td>
                    <?php foreach ($titles as $key => $title) : ?>
                        <?php foreach ($skus as $sku) : ?>

                            <?php foreach ($ages as $age) : ?>

                                <td style="background-color: #accb7e; word-break: keep-all; white-space: nowrap">
                                    <small><?= $block->escapeHtml($age === 0 ? __('Global') : $block->getAgeName($age)) ?></small>
                                </td>

                            <?php endforeach; ?>


                        <?php endforeach; ?>

                    <?php endforeach; ?>
                </tr>


                <?php $i = 0;
                foreach ($days as $day) :
                    $i++; ?>
                    <tr class="<?= $block->escapeHtmlAttr(($i % 2) ? 'even' : '') ?>">

                        <td class=" no-link right col-number" style=" word-break: keep-all; white-space: nowrap">
                            <span><?= /* @noEscape */
                                $block->formatPeriodColumn($day) ?></span>
                        </td>
                        <?php foreach ($titles as $key => $title) :
                            ?>

                            <?php foreach ($skus as $sku) : ?>

                            <?php foreach ($ages as $age) : ?>

                                <td class=" no-link right col-number"
                                    style=" background-color: <?php $default = isset($bgcolor[$sku]) ? $bgcolor[$sku] : '';
                                    echo $block->getBackgroundColor(
                                        $key,
                                        $collection[$sku][$day],
                                        $ages,
                                        $age,
                                        $default
                                    ); ?>">
                                    <span><?= $block->getRowValue(
                                            $key,
                                            $collection[$sku][$day][$age][$key]
                                        ); ?></span>
                                </td>

                            <?php endforeach; ?>


                        <?php endforeach; ?>

                        <?php endforeach; ?>
                    </tr>

                <?php endforeach; ?>

            <?php else : ?>

                <?php $i = 0;

                foreach ($days as $day) :
                    $i++; ?>

                    <?php foreach ($ages as $age) : ?>

                    <tr class="<?= $block->escapeHtmlAttr(($i % 2) ? 'even' : '') ?>">
                        <td class=" no-link right col-number" style=" word-break: keep-all; white-space: nowrap">
                            <span><?= /* @noEscape */
                                $block->formatPeriodColumn($day) ?></span>
                        </td>
                        <?php foreach ($titles as $key => $title) : ?>

                            <?php foreach ($skus as $sku) : ?>

                                <td class=" no-link right col-number"
                                    style=" background-color: <?php $default = 'whitesmoke';
                                    echo $block->getBackgroundColorProducts(
                                        $key,
                                        $collection,
                                        $sku,
                                        $default,
                                        $day,
                                        $skus
                                    ); ?>">

                                        <span><?= $block->getRowValue(
                                                $key,
                                                $collection[$sku][$day][$age][$key]
                                            ); ?></span>
                                </td>

                            <?php endforeach; ?>

                        <?php endforeach; ?>

                    </tr>

                <?php endforeach; ?>

                <?php endforeach; ?>
            <?php endif; ?>

            </tbody>

            <tfoot>
            <tr class="totals">
                <th class=" no-link right" style="text-align: right">
                    <span></span></th>
                <?php foreach ($titles as $key => $title) : ?>

                    <?php foreach ($skus as $sku) : ?>

                        <?php foreach ($ages as $age) : ?>

                            <th class=" no-link right" style="text-align: right">
                                <span><?= /* @noEscape */
                                    $block->getTotalForColumn($key, $sku, $age) ?></span></th>

                        <?php endforeach; ?>

                    <?php endforeach; ?>

                <?php endforeach; ?>

            </tr>

            </tfoot>
        </table>
        <?php endif; ?>
    </div>
</div>